image: python:3.7.3

stages:
  - test
  - deploy

test:
  stage: test
  before_script:
    - pip3 install virtualenv
    - make setup
  script:
    - make

deploy:
  stage: deploy
  only:
    - /^v\d+\.\d+\.\d+$/
  script:
    - make release
